import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'
import { AuthProvider } from '@/context/authcontext'

const inter = Inter({
    subsets: ['latin'],
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body
                data-theme='light'
                className={inter.className}
                suppressHydrationWarning={true}
            >
                <Toaster position='top-right' />
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    )
}
